% Auto-generated by plotting_gui.py
rawPath = 'D:/FEDL/Data/FEDL_Data/plotting/raw_data.csv';
outputDir = 'D:/FEDL/Data/FEDL_Data/final/outputs';
xColumn = 'V1';
yColumn = 'Abs_Id';
xScale = 'linear';
yScale = 'log';
xLabelText = 'V1';
yLabelText = 'Abs_Id';
axisCfg = struct('xMin', str2double(''), 'xMax', str2double(''), 'yMin', str2double(''), 'yMax', str2double(''), 'xMajor', str2double(''), 'xMinorCount', str2double(''), 'yMajor', str2double(''), 'yMinorCount', str2double(''), 'xReverse', false, 'yReverse', false);
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end
groups = [struct('name', 'Sweep1', 'series', [struct('source_file', '20 2 DS.csv', 'setup_title', 'Nega Sweep(1)(1)'), struct('source_file', '20 2 DS.csv', 'setup_title', 'Posi Sweep(1)(1)')]),
    struct('name', 'Sweep2', 'series', [struct('source_file', '20 3 DS.csv', 'setup_title', 'Nega Sweep(2)(1)'), struct('source_file', '20 3 DS.csv', 'setup_title', 'Posi Sweep(2)(1)')]),
    struct('name', 'Sweep3', 'series', [struct('source_file', '20 4 DS.csv', 'setup_title', 'Nega Sweep(3)(1)'), struct('source_file', '20 4 DS.csv', 'setup_title', 'Posi Sweep(3)(1)')]),
    struct('name', 'Sweep4', 'series', [struct('source_file', '20 0 DS.csv', 'setup_title', 'Nega Sweep(4)(1)'), struct('source_file', '20 0 DS.csv', 'setup_title', 'Posi Sweep(4)(1)')]),
    struct('name', 'Sweep5', 'series', [struct('source_file', '20 1 DS.csv', 'setup_title', 'Nega Sweep(5)'), struct('source_file', '20 1 DS.csv', 'setup_title', 'Posi Sweep(5)')])];
plots = [struct('name', 'Plot1', 'groups', {{'Sweep1', 'Sweep2', 'Sweep3', 'Sweep4', 'Sweep5'}})];
formatFlags = struct('png', true);
palette = [
    1.00 0.33 0.35;
    1.00 0.64 0.29;
    0.33 1.00 0.29;
    0.34 0.67 1.00;
    0.57 0.30 0.98;
    0.92 0.82 0.31;
    0.27 0.88 0.85;
    1.00 0.45 0.74
];
T = readtable(rawPath, 'TextType', 'string');
T = normalize_raw_table(T, xColumn, yColumn);
for plotIndex = 1:numel(plots)
    plotDef = plots(plotIndex);
    groupData = repmat(struct('name', "", 'table', table(), 'provenance', strings(0, 1)), 1, numel(plotDef.groups));
    for groupIndex = 1:numel(plotDef.groups)
        groupDef = find_group(groups, plotDef.groups{groupIndex});
        groupData(groupIndex) = build_group_data(T, groupDef);
    end
    render_plot(plotDef.name, xColumn, yColumn, xScale, yScale, xLabelText, yLabelText, axisCfg, groupData, palette, outputDir, formatFlags);
end

function T = normalize_raw_table(T, xColumn, yColumn)
    neededText = ["source_file", "setup_title", "source_line"];
    for idx = 1:numel(neededText)
        if ismember(neededText(idx), string(T.Properties.VariableNames))
            T.(neededText(idx)) = string(T.(neededText(idx)));
        end
    end

    numericTargets = unique(string({char(xColumn), char(yColumn)}));
    for idx = 1:numel(numericTargets)
        name = numericTargets(idx);
        if ismember(name, string(T.Properties.VariableNames))
            T.(name) = str2double(string(T.(name)));
        end
    end

    keepMask = true(height(T), 1);
    if ismember("source_file", string(T.Properties.VariableNames))
        keepMask = keepMask & strlength(strtrim(T.source_file)) > 0;
    end
    if ismember("setup_title", string(T.Properties.VariableNames))
        keepMask = keepMask & strlength(strtrim(T.setup_title)) > 0;
    end
    T = T(keepMask, :);
end

function groupDef = find_group(groups, groupName)
    for idx = 1:numel(groups)
        if strcmp(groups(idx).name, groupName)
            groupDef = groups(idx);
            return;
        end
    end
    error('Unknown group: %s', groupName);
end

function groupData = build_group_data(T, groupDef)
    rows = T([],:);
    provenance = strings(0, 1);
    for idx = 1:numel(groupDef.series)
        ref = groupDef.series(idx);
        mask = T.source_file == string(ref.source_file) & T.setup_title == string(ref.setup_title);
        subset = T(mask, :);
        if ismember('source_line', subset.Properties.VariableNames)
            subset.source_line_num = str2double(string(subset.source_line));
            subset = sortrows(subset, 'source_line_num');
            subset.source_line_num = [];
        end
        rows = [rows; subset]; %#ok<AGROW>
        provenance(end + 1, 1) = string(ref.source_file) + " / " + string(ref.setup_title); %#ok<AGROW>
    end
    groupData = struct('name', groupDef.name, 'table', rows, 'provenance', provenance);
end

function render_plot(plotName, xColumn, yColumn, xScale, yScale, xLabelText, yLabelText, axisCfg, groupData, palette, outputDir, formatFlags)
    fig = figure('Color', 'white', 'InvertHardcopy', 'off', 'Position', [60, 60, 860, 860], 'Visible', 'off');
    layout = tiledlayout(fig, 5, 1, 'TileSpacing', 'compact', 'Padding', 'compact');
    ax = nexttile(layout, [4 1]);
    hold(ax, 'on');
    style_axes(ax);
    ax.XScale = lower(char(xScale));
    ax.YScale = lower(char(yScale));
    title(ax, compose_title(plotName, xColumn, yColumn), 'Color', 'black', 'FontSize', 18, 'FontWeight', 'bold');

    messages = strings(0, 1);
    legendEntries = strings(0, 1);
    plotted = 0;

    for idx = 1:numel(groupData)
        color = palette(mod(idx - 1, size(palette, 1)) + 1, :);
        [x, y, ok, note] = extract_xy(groupData(idx).table, xColumn, yColumn, xScale, yScale);
        if ~ok
            messages(end + 1, 1) = groupData(idx).name + " skipped: " + note; %#ok<AGROW>
            continue;
        end
        builtin('plot', ax, x, y, 'LineWidth', 2.8, 'Color', color);
        plotted = plotted + 1;
        legendEntries(end + 1, 1) = string(groupData(idx).name); %#ok<AGROW>
    end

    if plotted == 0
        text(ax, 0.5, 0.5, 'No plottable data for the selected columns.', 'Units', 'normalized', 'HorizontalAlignment', 'center', 'Color', 'black', 'FontSize', 14);
    else
        apply_axis_settings(ax, axisCfg, xScale, yScale);
        legend(ax, legendEntries, 'TextColor', 'black', 'Color', 'white', 'EdgeColor', [0.7 0.7 0.7], 'Location', 'eastoutside');
    end

    xlabel(ax, xLabelText, 'Color', 'black', 'FontSize', 14, 'FontWeight', 'bold');
    ylabel(ax, yLabelText, 'Color', 'black', 'FontSize', 14, 'FontWeight', 'bold');
    notes = build_note_lines(groupData, messages);
    detailAx = nexttile(layout);
    render_details_panel(detailAx, notes);
    export_figure(fig, plotName, xColumn, yColumn, yScale, outputDir, formatFlags);
    close(fig);
end

function [x, y, ok, note] = extract_xy(T, xColumn, yColumn, xScale, yScale)
    ok = false;
    note = "";
    x = [];
    y = [];
    if ~ismember(xColumn, string(T.Properties.VariableNames))
        note = "missing x column";
        return;
    end
    if ~ismember(yColumn, string(T.Properties.VariableNames))
        note = "missing y column";
        return;
    end
    x = T.(xColumn);
    y = T.(yColumn);
    keep = isfinite(x) & isfinite(y) & ~isnan(x) & ~isnan(y);
    if strcmpi(xScale, 'log')
        keep = keep & x > 0;
    end
    if strcmpi(yScale, 'log')
        keep = keep & y > 0;
    end
    x = x(keep);
    y = y(keep);
    ok = numel(x) >= 2;
    if ~ok
        note = "not enough valid numeric points";
    end
end

function titleText = compose_title(plotName, xColumn, yColumn)
    titleText = char(string(plotName) + " | " + string(yColumn) + " - " + string(xColumn));
end

function notes = build_note_lines(groupData, messages)
    notes = strings(0, 1);
    for idx = 1:numel(groupData)
        notes(end + 1, 1) = string(groupData(idx).name) + " <- " + strjoin(groupData(idx).provenance, ', '); %#ok<AGROW>
    end
    for idx = 1:numel(messages)
        notes(end + 1, 1) = messages(idx); %#ok<AGROW>
    end
end

function render_details_panel(ax, notes)
    axis(ax, 'off');
    ax.Color = 'none';
    if isempty(notes)
        return;
    end
    text(ax, 0.01, 0.95, cellstr(notes), 'Units', 'normalized', 'VerticalAlignment', 'top', 'HorizontalAlignment', 'left', 'Interpreter', 'none', 'Color', 'black', 'FontSize', 10);
end

function apply_axis_settings(ax, cfg, xScale, yScale)
    hasXMin = ~isnan(cfg.xMin);
    hasXMax = ~isnan(cfg.xMax);
    hasYMin = ~isnan(cfg.yMin);
    hasYMax = ~isnan(cfg.yMax);

    if hasXMin && hasXMax && cfg.xMin < cfg.xMax
        if strcmpi(xScale, 'log') && cfg.xMin > 0
            xlim(ax, [cfg.xMin, cfg.xMax]);
        elseif ~strcmpi(xScale, 'log')
            xlim(ax, [cfg.xMin, cfg.xMax]);
        end
    else
        xlim(ax, 'tight');
    end

    if hasYMin && hasYMax && cfg.yMin < cfg.yMax
        if strcmpi(yScale, 'log')
            if cfg.yMin > 0
                ylim(ax, [cfg.yMin, cfg.yMax]);
            end
        else
            ylim(ax, [cfg.yMin, cfg.yMax]);
        end
    end

    if cfg.xReverse
        ax.XDir = 'reverse';
    end
    if cfg.yReverse
        ax.YDir = 'reverse';
    end

    if ~isnan(cfg.xMajor) && cfg.xMajor > 0
        if strcmpi(xScale, 'log')
            xt = build_log_ticks(xlim(ax), cfg.xMajor);
        else
            xt = build_linear_ticks(xlim(ax), cfg.xMajor);
        end
        if numel(xt) >= 2
            ax.XTick = xt;
        end
    end

    if ~isnan(cfg.yMajor) && cfg.yMajor > 0
        if strcmpi(yScale, 'log')
            yt = build_log_ticks(ylim(ax), cfg.yMajor);
        else
            yt = build_linear_ticks(ylim(ax), cfg.yMajor);
        end
        if numel(yt) >= 2
            ax.YTick = yt;
        end
    end

    if ~isnan(cfg.xMinorCount) && cfg.xMinorCount > 0
        ax.XMinorTick = 'on';
        if ~isnan(cfg.xMajor) && cfg.xMajor > 0 && ~strcmpi(xScale, 'log')
            step = cfg.xMajor / (cfg.xMinorCount + 1);
            xmt = build_linear_ticks(xlim(ax), step);
            if numel(xmt) >= 3
                ax.XRuler.MinorTickValues = xmt;
            end
        end
    end

    if ~isnan(cfg.yMinorCount) && cfg.yMinorCount > 0
        ax.YMinorTick = 'on';
        if ~isnan(cfg.yMajor) && cfg.yMajor > 0 && ~strcmpi(yScale, 'log')
            step = cfg.yMajor / (cfg.yMinorCount + 1);
            ymt = build_linear_ticks(ylim(ax), step);
            if numel(ymt) >= 3
                ax.YRuler.MinorTickValues = ymt;
            end
        end
    end
    draw_top_right_border(ax);
end

function ticks = build_linear_ticks(rng, step)
    lo = min(rng);
    hi = max(rng);
    if ~isfinite(lo) || ~isfinite(hi) || step <= 0 || hi <= lo
        ticks = [];
        return;
    end
    startValue = ceil(lo / step) * step;
    endValue = floor(hi / step) * step;
    if endValue < startValue
        ticks = [];
        return;
    end
    ticks = startValue:step:endValue;
end

function ticks = build_log_ticks(rng, decadeStep)
    lo = min(rng);
    hi = max(rng);
    if lo <= 0 || hi <= lo
        ticks = [];
        return;
    end
    step = max(1, round(decadeStep));
    p0 = floor(log10(lo));
    p1 = ceil(log10(hi));
    ticks = 10 .^ (p0:step:p1);
end

function draw_top_right_border(ax)
    delete(findobj(ax, 'Type', 'line', 'Tag', 'manual_top_border'));
    delete(findobj(ax, 'Type', 'line', 'Tag', 'manual_right_border'));
    xl = xlim(ax);
    yl = ylim(ax);
    line(ax, xl, [yl(2) yl(2)], 'Color', ax.XColor, 'LineWidth', ax.LineWidth, 'Tag', 'manual_top_border', 'HandleVisibility', 'off', 'Clipping', 'off');
    line(ax, [xl(2) xl(2)], yl, 'Color', ax.YColor, 'LineWidth', ax.LineWidth, 'Tag', 'manual_right_border', 'HandleVisibility', 'off', 'Clipping', 'off');
end

function export_figure(fig, plotName, xColumn, yColumn, yScale, outputDir, formatFlags)
    baseName = sanitize_filename(string(plotName) + "_" + string(xColumn) + "_" + string(yColumn) + "_" + string(yScale));
    if formatFlags.png
        exportgraphics(fig, fullfile(outputDir, baseName + ".png"), 'Resolution', 300, 'BackgroundColor', 'none');
    end
end

function style_axes(ax)
    ax.Color = 'none';
    ax.XColor = 'black';
    ax.YColor = 'black';
    ax.GridColor = [0.80 0.80 0.80];
    ax.MinorGridColor = [0.90 0.90 0.90];
    ax.YMinorGrid = 'on';
    ax.FontSize = 12;
    ax.LineWidth = 1.2;
    grid(ax, 'on');
    ax.Box = 'off';
    ax.TickDir = 'out';
    ax.XAxisLocation = 'bottom';
    ax.YAxisLocation = 'left';
end

function out = sanitize_filename(value)
    out = regexprep(char(value), '[^a-zA-Z0-9._-]+', '_');
end
